apiVersion: apps/v1
kind: Deployment
metadata:
  name: kayenta
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: us-docker.pkg.dev/spinnaker-community/docker/kayenta:spinnaker-master-latest-validated
        name: kayenta
        ports:
        - name: traffic-port
          containerPort: 8090
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: kayenta-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 720
      volumes:
      - name: kayenta-config-volume
        secret:
          secretName: kayenta-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 10111
        runAsGroup: 10111
        runAsNonRoot: true
        fsGroup: 10111
