services:
  clouddriverCaching:
    baseUrl: http://clouddriver-caching.spinnaker:7002
    enabled: true
  clouddriverRo:
    baseUrl: http://clouddriver-ro.spinnaker:7002
    enabled: true
  clouddriverRoDeck:
    baseUrl: http://clouddriver-ro-deck.spinnaker:7002
    enabled: true
  clouddriverRw:
    baseUrl: http://clouddriver-rw.spinnaker:7002
    enabled: true
  echoScheduler:
    baseUrl: http://echo-scheduler.spinnaker:8089
    enabled: true
  echoWorker:
    baseUrl: http://echo-worker.spinnaker:8089
    enabled: true
  redis:
    baseUrl: redis://redis.spinnaker:6379
    enabled: true
  redisRo:
    # For now just pointing at the primary redis
    # Consider pointing to a spin-redis-ro service
    baseUrl: redis://redis.spinnaker:6379
    enabled: true

