apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/gate:spinnaker-master-latest-validated
        name: gate
        ports:
        - name: traffic-port
          containerPort: 8084
          protocol: TCP
        readinessProbe:
          httpGet:
            # TODO(ezimanyi): we need some way of making this scheme configurable
            # so the health check passes without SSL enabled.
            scheme: HTTPS
            port: traffic-port
            path: /health
        resources:
          requests:
            memory: 1Gi
            cpu: 500m
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: gate-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 720
      volumes:
      - name: gate-config-volume
        secret:
          secretName: gate-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
