apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
      app.kubernetes.io/instance: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
        app.kubernetes.io/instance: echo
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/echo:spinnaker-master-latest-unvalidated
        name: echo
        ports:
        - name: traffic-port
          containerPort: 8089
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 800m
            memory: 1200Mi
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: echo-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: echo-config-volume
        secret:
          secretName: echo-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
