apiVersion: apps/v1
kind: Deployment
metadata:
  name: front50
  labels:
    app.kubernetes.io/name: front50
    app.kubernetes.io/instance: front50
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: front50
      app.kubernetes.io/instance: front50
  template:
    metadata:
      labels:
        app.kubernetes.io/name: front50
        app.kubernetes.io/instance: front50
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/front50:spinnaker-master-latest-unvalidated
        name: front50
        ports:
        - name: traffic-port
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: front50-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      terminationGracePeriodSeconds: 720
      volumes:
      - name: front50-config-volume
        secret:
          secretName: front50-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets

