apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddriver
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/clouddriver:spinnaker-master-latest-validated
        name: clouddriver
        ports:
        - name: traffic-port
          containerPort: 7002
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
        resources:
          requests:
            cpu: 800m
            memory: 1200Mi
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: clouddriver-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 720
      volumes:
      - name: clouddriver-config-volume
        secret:
          secretName: clouddriver-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
