apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./clouddriver-caching
- ./clouddriver-rw
- ./clouddriver-ro
- ./clouddriver-ro-deck
secretGenerator:
- files: []
  name: clouddriver-config
