apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app.kubernetes.io/name: clouddriver
    app.kubernetes.io/instance: clouddriver
  name: clouddriver
spec:
  ports:
  - port: 7002
    protocol: TCP
    targetPort: 7002
  selector:
    app.kubernetes.io/name: clouddriver
    app.kubernetes.io/instance: clouddriver
  type: LoadBalancer
