apiVersion: apps/v1
kind: Deployment
metadata:
  name: front50
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=80.0
        - name: SPRING_PROFILES_ACTIVE
          value: local
        image: gcr.io/spinnaker-marketplace/front50:spinnaker-master-latest-validated
        name: front50
        ports:
        - name: traffic-port
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            port: traffic-port
            path: /health
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: front50-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
        securityContext:
          allowPrivilegeEscalation: false
      terminationGracePeriodSeconds: 720
      volumes:
      - name: front50-config-volume
        secret:
          secretName: front50-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
