apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./clouddriver
- ./echo
- ./front50
commonLabels:
  app.kubernetes.io/component: server
  app.kubernetes.io/managed-by: kleat
  app.kubernetes.io/part-of: spinnaker
  app.kubernetes.io/version: 1.18.2
secretGenerator:
- behavior: merge
  files:
  - config/spinnaker.yml
  name: clouddriver-config
namespace: spinnaker
