apiVersion: apps/v1
kind: Deployment
metadata:
  name: keel
  namespace: spinnaker
spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -XX:MaxRAMPercentage=50.0
        image: docker.io/nimak/spinnaker-keel:latest
        name: keel
        ports:
        - containerPort: 7010
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:7010/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: keel-config-volume
        - mountPath: /var/secrets
          name: spinnaker-secrets-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: keel-config-volume
        secret:
          defaultMode: 420
          secretName: keel-config
      - name: spinnaker-secrets-volume
        secret:
          secretName: spinnaker-secrets
